### ISSUE TITLE
Filevault 2 detailed status High Sierra

### ISSUE THREAD

**Issue by brtr92** [homebysix/jss-filevault-reissue#10]
On computers with high sierra it says " FileVault 2 Detailed Status:
FileVault 2 Encryption Not Enabled " but its encrypted and i cannot get the Filevault key in Jamf pro.

**Comment by homebysix** [comment]
Hi @brtr92. This is almost certainly an issue with the FileVault 2 Detailed Status extension attribute, and not with the reissue script. I suspect it's this one: https://github.com/rtrouton/rtrouton_scripts/issues/32

**Comment by thefad3d** [comment]
Rich has created another EA for APFS: 
https://github.com/rtrouton/rtrouton_scripts/tree/master/rtrouton_scripts/Casper_Extension_Attributes/check_apfs_encryption
