### ISSUE TITLE
"Sorry, an error occurred while escrowing your FileVault key" 

### ISSUE THREAD

**Issue by br3ck** [homebysix/jss-filevault-reissue#14]
Hi there, 

Thanks much for this brilliant mechanism! Very easy to build out and worked almost flawlessly but I am getting an error that the key can't be escrowed to the JSS. Confirmed that the High Sierra compatible config profile is indeed installed on the machine which should tell the endpoint where to send the key however I am not having much luck. Any advice would be most appreciated. 

I am on 10.13.2 FWIW

**Comment by br3ck** [comment]
I'm all set. It was just the one endpoint that was being a jerk. Working great now! Thanks much!

**Comment by homebysix** [comment]
Good to hear! Thanks for the update.
