### ISSUE TITLE
No Popups Displayed

### ISSUE THREAD

**Issue by manicslothpdx** [homebysix/jss-filevault-reissue#2]
A while ago (maybe last year,) this script or a previous version of it would not show the popups when set to run via a "recurring check-in" policy in Casper. Did this issue potentially start happening again? I hadn't tried this in a while, but I just recently updated our existing policy with the newest version of the script. When I set this script to run via such a policy, I get the following logs but the user never saw the popup. The target Mac is running 10.11.6 and I followed the instructions exactly as specified:

Executing Policy SFDC Reissue FileVault Key (Check-in)
Running script SFDC Reissue New FileVault Key...
Script exit code: 239
Script result: Alerting user ed.cripps about incoming password prompt...
0Prompting ed.cripps for their Mac password...
Prompting ed.cripps for their Mac password (attempt 2)...
Prompting ed.cripps for their Mac password (attempt 3)...
Prompting ed.cripps for their Mac password (attempt 4)...
Prompting ed.cripps for their Mac password (attempt 5)...
[ERROR] Password prompt unsuccessful after 5 attempts.
Error running script: return code was 239.

**Comment by manicslothpdx** [comment]
However, just like before, if I manually call the policy via `sudo jamf policy -event name_of_policy` it works fine.

**Comment by manicslothpdx** [comment]
I found this previous thread from the older version of the script, but it looks to me like the new script may have regressed: https://github.com/homebysix/misc/pull/8

Also, I found this comment: https://github.com/homebysix/misc/commit/9a6cb4ccda6853b9d90840d617c86e191bb02a35

And, this comment: "Thanks to @benmartel for the "run AppleScript as current user" idea."

**Comment by manicslothpdx** [comment]
I diff'd the "fixed" version with the one currently located here, made some changes and it immediately started working. However, I may still need to assistance because now, after clicking "OK" on the first window, it appears you always get an incorrect password error as the first version of the 2nd popup. Entering the password results in success, but I can't figure out why the first of that popup says "incorrect password."

**Comment by manicslothpdx** [comment]
Following up on my last comment, the "incorrect password" popup only is displayed when the script is executed via Casper. If I copy the script to my Mac and run it manually, it successfully shows the "Enter Password" popup.

**Comment by manicslothpdx** [comment]
By the way, the only thing I had to change to your script to make it work was to line 76:

`LOGO_ICNS="$(/usr/bin/osascript -e 'tell application "System Events" to return POSIX file "'"$LOGO_ICNS"'" as text')"`

I think by specifying the full path to /usr/bin/osascript just once, that resolves the initial issue. I think. But, I still have no idea why the issue with the "incorrect password" is occurring. Other than customizations to the body text and links to icons, line 76 was the only change I made.

**Comment by homebysix** [comment]
Hi @manicslothpdx,

Thanks for the troubleshooting! I took your advice and added the full path to `osascript` to the latest version of this script. Can you try out version 1.7 and let me know how it goes? Thanks!

**Comment by m3ir** [comment]
Hi @homebysix 

been trying using v1.7.1  , with no change and without using logo/icons 
I get the same issue  , no popup and prompt of wrong password .

> Script exit code: 1
Script result: /Library/Application Support/JAMF/tmp/reissue_filevault_recovery_key: line 1: ill: command not found
Alerting user perfecto about incoming password prompt...
Prompting perfecto for their Mac password...
Prompting perfecto for their Mac password (attempt 2)...
Prompting perfecto for their Mac password (attempt 3)...
Prompting perfecto for their Mac password (attempt 4)...
Prompting perfecto for their Mac password (attempt 5)...
[ERROR] Password prompt unsuccessful after 5 attempts. Displaying "forgot password" message...
Error running script: return code was 1.<

**Comment by homebysix** [comment]
Hi @m3ir,

This line tells me something's wrong:

```
Script result: /Library/Application Support/JAMF/tmp/reissue_filevault_recovery_key: line 1: ill: command not found
```

Please make sure you copied/pasted the script in its entirety to the JSS "scripts" interface. You shouldn't get any "command not found" errors if it's working correctly.

**Comment by homebysix** [comment]
@manicslothpdx Have you tried version 1.7+ recently? Interested to hear whether your original issue is solved.

**Comment by manicslothpdx** [comment]
Hmmm, sorry. I thought I posted my results. I guess not. I tried version 1.7 but not version 1.7.1. The 1.7 version worked fine for our environment. Thanks for making that change.

However, I’ll be honest. I ended up switching this process to a **silent** alternative called "fde-rekey" which has worked well for us too:

https://github.com/square/fde-rekey

It's a package you deploy that silently accomplishes the same thing as this script.

**Comment by m3ir** [comment]
Hi @homebysix 

sure the script is entirely to the JSS scripts , tho I need to remove the icon lines else it gives me errors on it and now it looks like this  :
`#!/bin/bash

###
#
#            Name:  reissue_filevault_recovery_key.sh
#     Description:  This script is intended to run on Macs which no longer have
#                   a valid recovery key in the JSS. It prompts users to enter
#                   their Mac password, and uses this password to generate a
#                   new FileVault key and escrow with the JSS. The "redirect
#                   FileVault keys to JSS" configuration profile must already
#                   be deployed in order for this script to work correctly.
#          Author:  Elliot Jordan <elliot@elliotjordan.com>
#         Created:  2015-01-05
#   Last Modified:  2017-02-22
#         Version:  1.7.1
#
###


################################## VARIABLES ##################################

# The title of the message that will be displayed to the user.
# Not too long, or it'll get clipped.
PROMPT_TITLE="Encryption Key Escrow"

# The body of the message that will be displayed before prompting the user for
# their password. All message strings below can be multiple lines.
PROMPT_MESSAGE="Your Mac's FileVault encryption key needs to be escrowed by PretendCo IT.

Click the Next button below, then enter your Mac's password when prompted."

# The body of the message that will be displayed after 5 incorrect passwords.
FORGOT_PW_MESSAGE="You made five incorrect password attempts.

Please contact the Help Desk at 555-1212 for help with your Mac password."

# The body of the message that will be displayed after successful completion.
SUCCESS_MESSAGE="Thank you! Your FileVault key has been escrowed."

# The body of the message that will be displayed if a failure occurs.
FAIL_MESSAGE="Sorry, an error occurred while escrowing your FileVault key. Please contact the Help Desk at 555-1212 for help."

# Optional but recommended: The profile identifier of the FileVault Key
# Redirection profile (e.g. ABCDEF12-3456-7890-ABCD-EF1234567890).
PROFILE_IDENTIFIER=""


###############################################################################
######################### DO NOT EDIT BELOW THIS LINE #########################
###############################################################################


######################## VALIDATION AND ERROR CHECKING ########################

# Suppress errors for the duration of this script. (This prevents JAMF Pro from
# marking a policy as "failed" if the words "fail" or "error" inadvertently
# appear in the script output.)
exec 2>/dev/null

BAILOUT=false

# Make sure we have root privileges (for fdesetup).
if [[ $EUID -ne 0 ]]; then
    echo "[ERROR] This script must run as root."
    BAILOUT=true
fi

# Bail out if jamfHelper doesn't exist.
jamfHelper="/Library/Application Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper"
if [[ ! -x "$jamfHelper" ]]; then
    echo "[ERROR] jamfHelper not found."
    BAILOUT=true
fi

# Most of the code below is based on the JAMF reissueKey.sh script:
# https://github.com/JAMFSupport/FileVault2_Scripts/blob/master/reissueKey.sh

# Check the OS version.
OS_MAJOR=$(sw_vers -productVersion | awk -F . '{print $1}')
OS_MINOR=$(sw_vers -productVersion | awk -F . '{print $2}')
if [[ "$OS_MAJOR" -ne 10 || "$OS_MINOR" -lt 9 ]]; then
    echo "[ERROR] OS version not 10.9+ or OS version unrecognized."
    sw_vers -productVersion
    BAILOUT=true
fi

# Check to see if the encryption process is complete
FV_STATUS="$(fdesetup status)"
if grep -q "Encryption in progress" <<< "$FV_STATUS"; then
    echo "[ERROR] The encryption process is still in progress."
    echo "$FV_STATUS"
    BAILOUT=true
elif grep -q "FileVault is Off" <<< "$FV_STATUS"; then
    echo "[ERROR] Encryption is not active."
    echo "$FV_STATUS"
    BAILOUT=true
elif ! grep -q "FileVault is On" <<< "$FV_STATUS"; then
    echo "[ERROR] Unable to determine encryption status."
    echo "$FV_STATUS"
    BAILOUT=true
fi

# Get the logged in user's name
CURRENT_USER="$(stat -f%Su /dev/console)"

# This first user check sees if the logged in account is already authorized with FileVault 2
FV_USERS="$(fdesetup list)"
if ! egrep -q "^${CURRENT_USER}," <<< "$FV_USERS"; then
    echo "[ERROR] $CURRENT_USER is not on the list of FileVault enabled users:"
    echo "$FV_USERS"
    BAILOUT=true
fi

# If specified, the FileVault key redirection profile needs to be installed.
if [[ "$PROFILE_IDENTIFIER" != "" ]]; then
    profiles -Cv | grep -q "profileIdentifier: $PROFILE_IDENTIFIER"
    if [[ $? -ne 0 ]]; then
        echo "[ERROR] The FileVault Key Redirection profile is not yet installed."
        BAILOUT=true
    fi
fi

# If any error occurred above, bail out.
if [[ "$BAILOUT" == "true" ]]; then
    exit 1
fi

################################ MAIN PROCESS #################################

# Get information necessary to display messages in the current user's context.
USER_ID=$(id -u "$CURRENT_USER")
if [[ "$OS_MAJOR" -eq 10 && "$OS_MINOR" -le 9 ]]; then
    L_ID=$(pgrep -x -u "$USER_ID" loginwindow)
    L_METHOD="bsexec"
elif [[ "$OS_MAJOR" -eq 10 && "$OS_MINOR" -gt 9 ]]; then
    L_ID=$USER_ID
    L_METHOD="asuser"
fi

# Display a branded prompt explaining the password prompt.
echo "Alerting user $CURRENT_USER about incoming password prompt..."
launchctl "$L_METHOD" "$L_ID" "$jamfHelper" -windowType "utility" -icon "$LOGO_PNG" -title "$PROMPT_TITLE" -description "$PROMPT_MESSAGE" -button1 "Next" -defaultButton 1 -startlaunchd &>/dev/null

# Get the logged in user's password via a prompt.
echo "Prompting $CURRENT_USER for their Mac password..."
USER_PASS="$(launchctl "$L_METHOD" "$L_ID" /usr/bin/osascript -e 'display dialog "Please enter the password you use to log in to your Mac:" default answer "" with title "'"${PROMPT_TITLE//\"/\\\"}"'" giving up after 86400 with text buttons {"OK"} default button 1 with hidden answer with icon file "'"${LOGO_ICNS//\"/\\\"}"'"' -e 'return text returned of result')"

# Thanks to James Barclay (@futureimperfect) for this password validation loop.
TRY=1
until dscl /Search -authonly "$CURRENT_USER" "$USER_PASS" &>/dev/null; do
    (( TRY++ ))
    echo "Prompting $CURRENT_USER for their Mac password (attempt $TRY)..."
    USER_PASS="$(launchctl "$L_METHOD" "$L_ID" /usr/bin/osascript -e 'display dialog "Sorry, that password was incorrect. Please try again:" default answer "" with title "'"${PROMPT_TITLE//\"/\\\"}"'" giving up after 86400 with text buttons {"OK"} default button 1 with hidden answer with icon file "'"${LOGO_ICNS//\"/\\\"}"'"' -e 'return text returned of result')"
    if (( TRY >= 5 )); then
        echo "[ERROR] Password prompt unsuccessful after 5 attempts. Displaying \"forgot password\" message..."
        launchctl "$L_METHOD" "$L_ID" "$jamfHelper" -windowType "utility" -icon "$LOGO_PNG" -title "$PROMPT_TITLE" -description "$FORGOT_PW_MESSAGE" -button1 'OK' -defaultButton 1 -startlaunchd &>/dev/null &
        exit 1
    fi
done
echo "Successfully prompted for Mac password."

# If needed, unload and kill FDERecoveryAgent.
if launchctl list | grep -q "com.apple.security.FDERecoveryAgent"; then
    echo "Unloading FDERecoveryAgent LaunchDaemon..."
    launchctl unload /System/Library/LaunchDaemons/com.apple.security.FDERecoveryAgent.plist
fi
if pgrep -q "FDERecoveryAgent"; then
    echo "Stopping FDERecoveryAgent process..."
    killall "FDERecoveryAgent"
fi

# Translate XML reserved characters to XML friendly representations.
# Thanks @AggroBoy! - https://gist.github.com/AggroBoy/1242257
USER_PASS_XML=$(echo "$USER_PASS" | sed -e 's~&~\&amp;~g' -e 's~<~\&lt;~g' -e 's~>~\&gt;~g' -e 's~\"~\&quot;~g' -e "s~\'~\&apos;~g" )

echo "Issuing new recovery key..."
FDESETUP_OUTPUT="$(fdesetup changerecovery -norecoverykey -verbose -personal -inputplist << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Username</key>
    <string>$CURRENT_USER</string>
    <key>Password</key>
    <string>$USER_PASS_XML</string>
</dict>
</plist>
EOF
)"

# Test success conditions.
FDESETUP_RESULT=$?
grep -q "Escrowing recovery key..." <<< "$FDESETUP_OUTPUT"
ESCROW_STATUS=$?
if [[ $FDESETUP_RESULT -ne 0 ]]; then
    echo "$FDESETUP_OUTPUT"
    echo "[WARNING] fdesetup exited with return code: $FDESETUP_RESULT."
    echo "See this page for a list of fdesetup exit codes and their meaning:"
    echo "https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/fdesetup.8.html"
    echo "Displaying \"failure\" message..."
    launchctl "$L_METHOD" "$L_ID" "$jamfHelper" -windowType "utility" -icon "$LOGO_PNG" -title "$PROMPT_TITLE" -description "$FAIL_MESSAGE" -button1 'OK' -defaultButton 1 -startlaunchd &>/dev/null &
elif [[ $ESCROW_STATUS -ne 0 ]]; then
    echo "$FDESETUP_OUTPUT"
    echo "[WARNING] FileVault key was generated, but escrow did not occur. Please verify that the redirection profile is installed and the Mac is connected to the internet."
    echo "Displaying \"failure\" message..."
    launchctl "$L_METHOD" "$L_ID" "$jamfHelper" -windowType "utility" -icon "$LOGO_PNG" -title "$PROMPT_TITLE" -description "$FAIL_MESSAGE" -button1 'OK' -defaultButton 1 -startlaunchd &>/dev/null &
else
    echo "$FDESETUP_OUTPUT"
    echo "Displaying \"success\" message..."
    launchctl "$L_METHOD" "$L_ID" "$jamfHelper" -windowType "utility" -icon "$LOGO_PNG" -title "$PROMPT_TITLE" -description "$SUCCESS_MESSAGE" -button1 'OK' -defaultButton 1 -startlaunchd &>/dev/null &
fi

exit $FDESETUP_RESULT
`
the error I get isn't script error , it's password error , and I get it cause of the popup not shows.

Regards,

**Comment by m3ir** [comment]
@homebysix

I need no logo/icons , so the script copied without these lines .
the script runs on computer , I get the first popup banner that explain about this script , clicking next popup to the last error banner  "you made five incorrect password attempts" . 
seems it bypass to input user password right to the error message .

> Running script reissue_filevault_recovery_key...
> Script exit code: 1
> Script result: Alerting user perfecto about incoming password prompt...
> Prompting perfecto for their Mac password...
> Prompting perfecto for their Mac password (attempt 2)...
> Prompting perfecto for their Mac password (attempt 3)...
> Prompting perfecto for their Mac password (attempt 4)...
> Prompting perfecto for their Mac password (attempt 5)...
> [ERROR] Password prompt unsuccessful after 5 attempts. Displaying "forgot password" message...
> Error running script: return code was 1.

**Comment by homebysix** [comment]
@manicslothpdx Thanks for letting me know about fde-rekey! That's pretty nifty, and I'm testing it out myself.

@m3ir I haven't tested the script's behavior when the logo variables are removed, since the script is meant to be company-branded. If you don't want to use your company logo, I suggest using a generic FileVault logo:

```
/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/FileVaultIcon.icns
```

**Comment by m3ir** [comment]
@manicslothpdx nice find! , just tested it and it works smoothly and most important silently .
@homebysix  I will give it a try .

Thanks you both!
