### ISSUE TITLE
This script is not yet supported on macOS Catalina

### ISSUE THREAD

**Issue by sjha967** [homebysix/jss-filevault-reissue#29]
Successfully prompted for Mac password.Checking for /var/db/FileVaultPRK.dat on macOS 10.13+...Issuing new recovery key...[WARNING] fdesetup exited with return code: 99.See this page for a list of fdesetup exit codes and their meaning:https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/fdesetup.8.htmlDisplaying "failure" message...
Error running script: return code was 99.

**Comment by homebysix** [comment]
Can you provide some context around this error? How many Macs are affected?

Does `sudo fdesetup changerecovery -personal -norecovery -verbose` work on the affected Mac(s)?

**Comment by charlespineda** [comment]
To his defense I mass deployed the script to several machines as well and have not been able to find any information on exit code 99 and I have a lot of machines affected by it.

```
Script result: No logo provided, or no logo exists at specified path. Using FileVault icon.
Alerting user gasubra about incoming password prompt...
Prompting user for their Mac password...
Prompting user for their Mac password (attempt 2)...
Successfully prompted for Mac password.
Checking for /var/db/FileVaultPRK.dat on macOS 10.13+...
Issuing new recovery key...
[WARNING] fdesetup exited with return code: 99.
Displaying "failure" message...
```
