### ISSUE TITLE
11.0.1 (20B50) - No password Popup appear

### ISSUE THREAD

**Issue by Siggloo** [homebysix/jss-filevault-reissue#37]
When testing the script on 11.0.1 no popups will be shown and fails on password.
Works in 10.15.7 without any issues.

From Jamf policy log:
Script result: [WARNING] This script has not been tested on macOS Big Sur. Use at your own risk.
Alerting user mikael.sigemo about incoming password prompt...
Prompting mikael.sigemo for their Mac password...
Prompting mikael.sigemo for their Mac password (attempt 2)...
Prompting mikael.sigemo for their Mac password (attempt 3)...
Prompting mikael.sigemo for their Mac password (attempt 4)...
Prompting mikael.sigemo for their Mac password (attempt 5)...
[ERROR] Password prompt unsuccessful after 5 attempts. Displaying "forgot password" message...

**Comment by macgod73** [comment]
@Siggloo 

I was seeing the same issue.  Beginning at line 157 I added the following elif statement for macOS 11.0 to populate the $L-METHOD variable.  This gets past the no popup issue, but is still failing.  I am still digging into it.

# Get information necessary to display messages in the current user's context.
USER_ID=$(/usr/bin/id -u "$CURRENT_USER")
if [[ "$OS_MAJOR" -eq 10 && "$OS_MINOR" -le 9 ]]; then
    L_ID=$(/usr/bin/pgrep -x -u "$USER_ID" loginwindow)
    L_METHOD="bsexec"
elif [[ "$OS_MAJOR" -eq 10 && "$OS_MINOR" -gt 9 ]]; then
    L_ID=$USER_ID
    L_METHOD="asuser"
elif [[ "$OS_MAJOR" -eq 11 && "$OS_MINOR" -ge 0 ]]; then
    L_ID=$USER_ID
    L_METHOD="asuser"
fi

**Comment by homebysix** [comment]
Thanks!

**Comment by Siggloo** [comment]
Awesome!
