### ISSUE TITLE
No Password Prompt In BigSur

### ISSUE THREAD

**Issue by vcasiero** [homebysix/jss-filevault-reissue#39]
i needed to modify the default logo for it to popup

had to change this code if a manual logo was not set...

# Validate logo file. If no logo is provided or if the file cannot be found at
# specified path, default to the FileVault icon.
if [[ -z "$LOGO" ]] || [[ ! -f "$LOGO" ]]; then
    /bin/echo "No logo provided, or no logo exists at specified path. Using FileVault icon."
    LOGO="/System/Library/PreferencePanes/Security.prefPane/Contents/Resources/SystemPreferences_Security.tiff"
fi

**Comment by homebysix** [comment]
Thanks! Could you try again with version 1.11.0?
