### ISSUE TITLE
Big Sur success condition does not work

### ISSUE THREAD

**Issue by macbofh** [homebysix/jss-filevault-reissue#40]
On Big Sur this script responds with "[WARNING] FileVault key was generated, but escrow cannot be confirmed. Please verify that the redirection profile is installed and the Mac is connected to the internet.".

It looks like the conditional check only checks for OS_MINOR >= 13, and this does not work with Big Sur because of the changed version numbering.

A quick and dirty fix is:
at the line after:
```
# Differentiate <=10.12 and >=10.13 success conditions 
```
change:
```
if [[ "$OS_MINOR" -ge 13 ]]; then
```
to
```
if [ "$OS_MINOR" -ge 13 ] | [ "$OS_MAJOR" -ge 11 ]; then
```

**Comment by homebysix** [comment]
Thanks!
