### ISSUE TITLE
Compatibility with BigSur

### ISSUE THREAD

**Issue by Mykolas2** [homebysix/jss-filevault-reissue#45]
Due version naming change to 11. for BigSur script wont pass version check when it is ran on BigSur. Can script be modified to work on BigSur? 

Example: Script result: [ERROR]: This script requires macOS 10.9 or higher. This Mac has 11.2.2.

**Comment by homebysix** [comment]
@Mykolas2 - Are you sure you're on the latest version of the script? Big Sur compatibility was [adjusted](https://github.com/homebysix/jss-filevault-reissue/commit/0c8cd92a14bc5b1b1a4d32030c4a264cc1206408) back in December.

**Comment by Mykolas2** [comment]
Sorry my bad. I'm using older version of the script. Will check corrected one.

**Comment by MOmogbehin** [comment]
i'm attempting to use this on a machine that's on Big Sur, verified i am indeed using the up to date version of the script and attempted to use 
`sudo fdesetup changerecovery -personal -norecovery -verbose` to change the key manually. that also returned an "unable to change key" error. any ideas?

**Comment by homebysix** [comment]
Off the top of my head, I'm not sure. Does the Mac have a PRK or might it be an IRK (institutional recovery key)?

In either case, I don't think it's an issue with the jss-filevault-reissue framework itself, so I'll close this issue.
