### ISSUE TITLE
FileVault.icns no longer present on Big Sur, resulting in no password prompts

### ISSUE THREAD

**Issue by UESCDurandal** [homebysix/jss-filevault-reissue#47]
We discovered that /System/Library/PreferencePanes/Security.prefPane/Contents/Resources/FileVault.icns is no longer present on Macs running Big Sur and in cases where our defined logo image is missing then the script will output the following logs without the actual prompt appearing on screen.

```
Script result: [WARNING] This script has not been tested on macOS Big Sur. Use at your own risk.
No logo provided, or no logo exists at specified path. Using FileVault icon.
Alerting user username about incoming password prompt...
Prompting username for their Mac password...
Prompting username for their Mac password (attempt 2)...
Prompting username for their Mac password (attempt 3)...
Prompting username for their Mac password (attempt 4)...
Prompting username for their Mac password (attempt 5)...
[ERROR] Password prompt unsuccessful after 5 attempts. Displaying "forgot password" message...
```

To fix this problem we have replaced that default path with /System/Library/PreferencePanes/Security.prefPane/Contents/Resources/SystemPreferences_Security.tiff instead, which is valid on at least Catalina and Big Sur.

**Comment by homebysix** [comment]
Hi @UESCDurandal - Please share what version of the script you're running in which you're encountering this problem. I believe it was [fixed](https://github.com/homebysix/jss-filevault-reissue/commit/a7d15466f33392d521423a5c7812eb5c1a2b4f1e) back in December.

**Comment by UESCDurandal** [comment]
Ah, my apologies I had thought I was running the latest with version 1.10.0. Nevermind!
