### ISSUE TITLE
"An error occurred" shown to user even though key escrowed to JSS

### ISSUE THREAD

**Issue by cattyv** [homebysix/jss-filevault-reissue#54]
## Summary

After an individual enrolls in Jamf Pro running macOS Monterey, they get a prompt in Self Service to click an button to run this script, if they already have Disk Encryption enabled (so their FileVault Encryption Key value is Invalid or Unknown.) After clicking this button in Self Service to run the script, they receive the following error: "Sorry, an error occurred while escrowing your FileVault key." But Personal Recovery Key does, in fact, escrow to JSS. The issue is we are seeing this error when it's not an error technically. I'm not sure what all the sudden caused this, outside of running macOS Monterey now. Any help is greatly appreciated! 

## Steps to Reproduce

Steps to reproduce the behavior.

## Versions

- reissue_filevault_recovery_key.sh version:
- macOS version:

## Additional Information

Any other context you'd like to share.

**Comment by homebysix** [comment]
Hello @cattyv - Could you please include which version of the reissue script you're using, and which specific macOS version you experience the error on? Thank you.

**Comment by cattyv** [comment]
Hi @homebysix - yes no problem. Version of Reissue Script: 1.11.0 and macOS Monterey Version 12.2.

**Comment by homebysix** [comment]
May you try again with the latest script version, 1.12.0?

**Comment by cattyv** [comment]
Hi @homebysix, version 1.12.0 fixed this issue. Awesome script - thanks so much.
