### ISSUE TITLE
Exit Error Code 99 Issue.

### ISSUE THREAD

**Issue by charlespineda** [homebysix/jss-filevault-reissue#58]
## Summary

@homebysix I mass deployed the script to a large group of employees who are coming from a previous MDM after testing with a group of 40 users most of them completed successfully. Deploying to the rest of the required computers many of them exited with exit code 99 and I am unable to understand what this means at this time. Any assistance would be appreciated.  

## Steps to Reproduce

Steps to reproduce the behavior.

## Expected/Desired Behavior
to escrow and complete successfully 

## Screenshots
![image](https://user-images.githubusercontent.com/66960882/218574428-ecd0f078-c638-4e84-ad2c-3a2fffcb8a27.png)

## Versions

- reissue_filevault_recovery_key.sh version: Latest version
- macOS version: 10.13 and up

## Additional Information

Any other context you'd like to share.

**Comment by homebysix** [comment]
According to [this page](https://www.unix.com/man-page/osx/8/fdesetup/), that's a pretty generic "internal error."

What happens if you manually run `sudo fdesetup changerecovery -personal` on an affected Mac?

**Comment by charlespineda** [comment]
fdesetup: do not return recovery key
fdesetup: use personal recovery key
fdesetup: device path = /
Enter the user name: `user`
Enter the password for user 'user':
Error: Unable to change key.
Error: User could not be authenticated.
Error: Unable to unlock or authenticate to FileVault.

**Comment by mpermann** [comment]
Do the user trying to run the command have a secure token?

**Comment by charlespineda** [comment]
Yes all of them do but I am noticing underlying issues here since these machines use MOBILE profiles a lot of them and I would say majority of them have sync issues and are using two separate passwords to login to their machines.

**Comment by mpermann** [comment]
I have no experience with bound machines using mobile profiles. Apple recommends against those anymore. If people have to enter two passwords to get into their computers then you defined have password sync issues which could explain why the FileVault re-keying is failing. You need to get the passwords back in sync.

**Comment by charlespineda** [comment]
Correct, I am working through some to confirm that is the case.

**Comment by charlespineda** [comment]
Confirmed that after syncing the MOBILE profile passwords and pushing out the Script again it worked fine.

**Comment by homebysix** [comment]
Glad to hear it!
